### ISSUE TITLE
Detailed Explanation please

### ISSUE THREAD

**Issue by M0stafaAhmed** [ZEraX4/E-ALPR#4]
**Hello there**
            I'm really happy with that great work
but I faced few issue while getting started with it
so if you can kindly explain a little more on the test picture attached or maybe upload a Video explains how to start 
Thanks Again for the really great work you've done on the **_E-ALPR_** and **_FRAS_**

**Comment by ZEraX4** [comment]
Hi @M0stafaAhmed ,

I noticed there was some errors happening due to some libraries updates, they should be fixed with the latest commit [1cf7627](https://github.com/ZEraX4/E-ALPR/commit/1cf7627c3deba5cf1aca45a34348ed6d99ce2e82).

The steps are fairly simple:

- First, you need to generate fonts data based on the plates fonts (Generate.py).
- Then, train the character model using the generated data (Train.py, --lite for GUI).
- Last, use the main script or the GUI to predict an image or a video (E-ALPR.py or E-ALPR_GUI.py for lite model).

You can read the [How to Use]( https://github.com/ZEraX4/E-ALPR#how-to-use) section for examples.
